### ISSUE TITLE
How to export and import segmentation in stack?

### ISSUE THREAD

**Issue by jlopes90** [cornerstonejs/cornerstone3D#1059]
I had done the export or import of segmentation in volume, here is the link https://github.com/cornerstonejs/cornerstone3D/issues/664

Now what's missing is stack, does anyone know?

**Comment by sedghi** [comment]
we haven't done the import into stack yet, we are busy unfortunatelly with a lot of new contour segmentations. I get free next week and I will triage this

**Comment by napest** [comment]
> we haven't done the import into stack yet, we are busy unfortunatelly with a lot of new contour segmentations. I get free next week and I will triage this

https://github.com/cornerstonejs/cornerstone3D/issues/1059#issuecomment-1943766789

**Comment by dima9911** [comment]
Hello dear @sedghi 
any update for this?
i try to export/input brush data with cornerstoneTools.segmentation.state any methods, but nothing help

Can you give some time estimate for this feature?

**Comment by sedghi** [comment]
Sorry I'm not understanding the question, I need more context

**Comment by dima9911** [comment]
@sedghi i have stack viewport with cornerstone3d library. 
1. i try to draw with brush tool circular on stack viewport, 
2. then i want export brush tool data, save to backend any format (for example annotation tools state -  json)
3. then redraw brush data to stack viewport with same dicom after page reload

**Comment by napest** [comment]
Hi Alireza @sedghi!
I'll add a bit more context.
We are developing a medical annotation tool. We need to export and import segmentations in some format. We found an example to export segmentation data to DICOM SEG, however:
1. We don't understand how we can import it
2. It doesn't work on stack viewports and we need segmentation on 2D images like mammograms/xray
The main criteria is to be able to draw segmentation -> save it on the server -> redraw it later
 
We (with dima9911) build it on vue js, so OHIF codebase on React doesn't help.

Could you please suggest a solution?

**Comment by sedghi** [comment]
As I mentioned the import and export from to stack viewport in DICOM SEG format is not done yet. So right now you can only create them. 

If you want to save it in any format then you can get the segmentation imageId, which is inside the `segmentation.state.getSegmentation(segmentationId)`, take a look inside the `imageIdReferenceMap` , then knowing your imageIds in the viewport (`viewport.getImageIds`) you can then find each segmentationImageId. 

Next you need to grab each segmentation image (`cache.getImage(segmentationImageId))`), then there you have the `getPixelData` that will be a typed array and you can decide how to send it to your server. 

Since labelmaps are usually sparse you can use RLE encoding to send less data over the network.

**Comment by sedghi** [comment]
The question regarding import is harder, 

# DICOM SEG import into stack viewport
We are working on writing that importer

# Custom data from backend import

You need to create a local image and set the pixelData from the data you recieve from the server, you can use this one `createAndCacheLocalImage`

**Comment by birdofpreyru** [comment]
+1 to the issue importance. I'm trying to figure out the way to export / import the results of segmentation by SplineContourSegmentationTool. I might be missing something, but:

1. Option A &mdash; I thought I can export the state of the created annotations, then import them... this fails because spline segmentation tool keeps in the annotation state instances of Spline (and probably some other classes). This gets wiped out if serialized / de-serialized. So, when imported the tool tries to call methods of the Spline instance inside the annotation state, and that crashes.

2. Option B &mdash; Exporting the segmentation as a polyline, then importing it as a geometry, and showing it... would work but `SegmentationDisplayTool` does not draw into stack viewports :(

3. Option C &mdash; Using 3D Volume viewport for segmentation & its rendering &mdash; fails for me because DICOM images I get have no imageOrientationPatient nor imagePositionPatient data (the images have XA modality). This crashes the volume loader. I kind of able to work it around with custom meta data providers injecting some made up orientation and position data, and thus avoiding the loader crash, but I end up with empty viewport... not sure because wrong values for orientation & position, or because something else is missing in these image metadata.

@sedghi can you advise something here? I am new to all this DICOM, medical imagery, and Cornerstone3D, thus might be missing something very basic here. It was kind of my basic assumption when signing up for a gig that if this library has segmentation tools that work on a image stack, the serialization / de-serialization of data they produce is a basic operation that should be supported... but after spending a way more time already on it than anticipated, and not being able to figure out the way, I am somewhat lost :(

**Comment by jlopes90** [comment]
I just made a new Segmentation Stack example, see here https://github.com/cornerstonejs/cornerstone3D/pull/1186

**Comment by tkt9k2562** [comment]
@jlopes90 
Thank you very much.  
Your example really works !

While I see a msg in console

![image](https://github.com/cornerstonejs/cornerstone3D/assets/16094044/4cae6289-a211-42d4-8468-7cb643d0f60a)

I can reproduce with steps:
1. `Demo Dicom`
2. Use `ThresholdCircle` tool to label it , then `Export Seg`
3. Refresh the page , then `Demo Dicom` and `Import Seg` 

Although it seems not affect how to load segmentation , it just only shows a msg in console

Would you have idea ?

**Comment by jlopes90** [comment]
@tkt9k2562 I cannot reproduce the error. If it works just ignore it for now.

**Comment by jlopes90** [comment]
@sedghi news? export segmentation format in dicom?

**Comment by sedghi** [comment]
not yet, it is on my todo list

**Comment by jlopes90** [comment]
I've already managed to "generate segmentation" in just one frame.
I've already tested an example "segmentation stack" edited dcmjs by node_module.

PR https://github.com/dcmjs-org/dcmjs/pull/395

**Comment by jlopes90** [comment]
I was just testing but I couldn't get my fork dcmjs.

[adapters/package.json](https://github.com/cornerstonejs/cornerstone3D/blob/main/packages/adapters/package.json#L47)
`"dcmjs": "^0.29.8"` to `"dcmjs": "github:jlopes90/fork-dcmjs#fix-generate-segmentation-only-one-frame"`

The result node_module: 
![image](https://github.com/cornerstonejs/cornerstone3D/assets/50026015/70560ddc-7da9-4022-a2d7-fec3596f5f3c)

**Comment by jlopes90** [comment]
There is another way without using this pull request https://github.com/dcmjs-org/dcmjs/pull/395

How does just one frame work:

```javascript
Cornerstone3D.Segmentation.generateSegmentation(
    [cacheImage, cacheImage],
    labelmapData,
    metaData
);
```

`[cacheImage, cacheImage]` both "cacheImage" are the same, just ignore it and it works only one frame.

**Comment by jlopes90** [comment]
I just updated the segmentation stack example (deploy)
https://deploy-preview-1336--cornerstone-3d-docs.netlify.app/live-examples/segmentationStack.html

PR https://github.com/cornerstonejs/cornerstone3D/pull/1336
