### ISSUE TITLE
Target Buffer Uint16 support?

### ISSUE THREAD

**Issue by Ouwen** [cornerstonejs/cornerstone3D#141]
I noticed that when loading the image we provide a target buffer of either Float32 or Uint8. In `cornerstonejs` I believe there was support for `Uint16` type. Larger medical image volumes (tomo) can be quite large when decompressed (200 slices of 2000x3000 uint16 pixels). This would translate to about 2.4GB if the native `Uint16` is used, but would double to 4.8GB using Float32.

I was curious if there were any challenges in supporting uint16 with the underlying vtk engine.

**Comment by swederik** [comment]
So there are a couple options. You need to minimize both RAM and VRAM but
their usage is not 1:1 depending on the WebGL internal format.

If you have a Uint16 array and pass it through the pipeline now it can be
mapped to half float as an internal format but this has less precision that
16 bits (see
https://en.m.wikipedia.org/wiki/Half-precision_floating-point_format) so it
might not completely accurately represent the image. If the range of the
image is within a specific range it will, though (I think something like
0-3000ish, it's in the half float conversion code in vtk).

There is another option which is here but it's not merged yet:
https://github.com/Kitware/vtk-js/pull/2058 which will allow Int16 to be
faithfully represented using the EXT_texture_norm16 extension. That is
probably a better option for the Tomo I think

Having said that, I think we would use a stack viewport for tomo and not
make one massive buffer anyway. Especially because the array buffer length
for the whole volume is likely going to exceed the chrome max array buffer
length of around 2gb.

**Comment by Ouwen** [comment]
Thanks for the above @swederik, just starting to revisit this issue now that [Kitware/vtk-js#2058](https://github.com/Kitware/vtk-js/pull/2058) is merged.

@sedghi, based on our conversation today... I was looking through where changes would need to have a cornerstone3D flag to use 16bit/half float. My understanding based on our conversation is that if the vtk mapper sets the `preferSizeOverAccuracy` flag to true it will properly use norm 16 or half float depending on the extensions available.

For norm16 and half float to be used, it requires the data provided to VTK to either be `UNSIGNED_SHORT` or `SHORT` (uint16/int16), but we currently type cast to Float32 in cornerstonejs

For half float implementation, it seems like the dynamic range is scaled to better fall in between [-2048, 2048] for accuracy purposes. For dicom pixel data, the BitsStored is usually smaller than BitsAllocated. For CT machines it is usually 12 bit stored and 16 bit allocated. Uint16 values beyond the BitsStored is typically burned in data where the dynamic range is less important. When we transition to the `UNSIGNED_SHORT` or `SHORT` dtype, it might make sense to clamp the data to BitsStored so the important part of the pixelData can be better preserved.

Here are the immediate code lines which might need to be changed:

https://github.com/cornerstonejs/cornerstone3D-beta/blob/d58c9fbe3f8bfc09aa9ece28f8ae1ca1141c2c7e/packages/core/src/RenderingEngine/vtkClasses/vtkStreamingOpenGLTexture.js#L59-L70

https://github.com/cornerstonejs/cornerstone3D-beta/blob/d58c9fbe3f8bfc09aa9ece28f8ae1ca1141c2c7e/packages/core/src/volumeLoader.ts#L234-L248

https://github.com/cornerstonejs/cornerstone3D-beta/blob/d58c9fbe3f8bfc09aa9ece28f8ae1ca1141c2c7e/packages/core/src/RenderingEngine/StackViewport.ts#L1198-L1223

https://github.com/cornerstonejs/cornerstone3D-beta/blob/d58c9fbe3f8bfc09aa9ece28f8ae1ca1141c2c7e/packages/streaming-image-volume-loader/src/cornerstoneStreamingImageVolumeLoader.ts#L109-L137

**Comment by sedghi** [comment]
Yeah I started this yesterday, there are some parts in wado that need to be changed too

**Comment by sedghi** [comment]
Hey, it is not a priority but on the roadmap

**Comment by sedghi** [comment]
Done in main branch
