### ISSUE TITLE
[Feature Request] Allow certain annotations to be rendered in any series with matching Frame-of-Refeence UID

### ISSUE THREAD

**Issue by John-Skinner** [cornerstonejs/cornerstone3D#1424]
### What feature or change would you like to see made?

We would like to be able to see ArrowAnnotation and our custom Arrow-like Annotation from any stack series or within volume viewports regardless of the viewport's slice orientation.  This feature request may be an overlap with 3d annotation rendering feature that is not available yet.

I would like to learn more about the plans for 3D annotation rendering to see if it would fulfill our use case.

The use case is the user uses a semi-automatic custom tool to mark spine disks with arrow-like annotations along sagittal views of the spine.  
When the user reviews slices from axial-like views, they can see the same arrow-like annotation that identifies which disk they are seeing.

I have implemented a prototype implementation covering only StackViewports.

`filterAnnotationForDisplay.ts`:
1) distinguish the cross-study toolNames (`annotation.metadata.toolName='ArrowAnnotate'`)
2) measure the distance from viewport slice plane to annotation's 1st handle in world coordinate.  If 'too far away', filter it out.

`StackViewport.ts`:
1) `isReferenceViewable`: if ArrowAnnotate type, then don't filter out annotation based on `referencedImageId`

Looking for design inputs

1) what threshold to use for the max distance from viewport's slice plane to the annotation's 1st handle in world coordinates.
2) a way to distinguish annotations that can be viewed from different series (a list of annotation names, or
the number of handle points plus the presence of arrowFirst property.  Many annotation types (Ellipse, length) have a
need to be viewed from a specific plane orientation (unless projected).

### Why should we prioritize this feature?

I am willing to prepare a pull request given some early guidance on the design.
The use case described above is important to our customers.

**Comment by sedghi** [comment]
This feature is understandable, but there's an issue. It's not just about viewing the annotation from different planes; you need to project it correctly onto the view plane. The challenge lies in the annotation's ability to project itself accurately across various planes, which is quite complex. Filtering alone isn't enough to solve this problem.

Create a new specialized tool called the arrow projection tool. When rendering the annotation in the render annotation function, instead of filtering for display, calculate the projection accurately based on the camera viewpoints. Display the annotation at the correct location, resulting in a single annotation shown in different planes.
