### ISSUE TITLE
Retaining Zoom/Camera settings with Cine Tool/Stack Frame change

### ISSUE THREAD

**Issue by jmannau** [cornerstonejs/cornerstone3D#181]
We use the Cine tool in Cornerstone v2 and the cine tool retains the zoom level when playing a stack or stepping through the frames.

With Cornerstone 3D, we are using 
```
viewport.setCamera({parallelScale}) 
```
to zoom in. However when using the Cine tool or changing the frame in the stack, the zoom level is reset.

Is it possible to retain the zoom/parallelScale setting when changing frames or using the cine tool with Cornerstone 3D?

**Comment by sedghi** [comment]
I think I know what is going on. Is your stack of images share the same metadata (spacing, orientation, etc.), or are they different set of images like axial CT, sagittal CT, .... in the same stack.

Basically, what is happening is that for performance reasons we are checking if the next image in the stack is part of the same 3D image as for [previous one](https://github.com/cornerstonejs/cornerstone3D-beta/blob/main/packages/core/src/RenderingEngine/StackViewport.ts#L1312-L1322), and if they are not we re-create the image again which reset the camera (since the camera need to move e.g., from axial to sagittal).

Check that function to see which one is not the same as before, our CINE tool keeps the camera, [look here](https://www.cornerstonejs.org/live-examples/cinetool)

**Comment by jmannau** [comment]
Thanks very much for pointing me in this direction.  The images I use have different columnPixelSpacing and rowPixelSpacing.  I think there is an issue here https://github.com/cornerstonejs/cornerstone3D-beta/blob/fe386dc89eacc58ada0d3b7217c960627168afe4/packages/core/src/RenderingEngine/StackViewport.ts#L1313-L1314


I believe that `xSpacing` should be compared to the `columnPixelSpacing` and `ySpacing` should be compared to `rowPixelSpacing`.

```
xSpacing !== image.columnPixelSpacing ||
ySpacing !== image.rowPixelSpacing ||
```

Let me know if I have that right and I'm happy to submit a PR.
