### ISSUE TITLE
[Bug] what's happening when we alt tab to another window and give input in that new window and come back to the browser?

### ISSUE THREAD

**Issue by shikamu** [cornerstonejs/cornerstone3D#733]
### Describe the Bug

I can use all sort of tools (pan, zoom, all the ROI tools) and then if I alt tab to another window and perform some actions in that new window (use mouse wheel for instance) and then come back to my browser with my cornerstone3d app, then I can't pan or use any of the ROI tools anymore

### Steps to Reproduce

1. have an external app open (visual studio, visual code, notepad++, whatever)
2. browse to one of the live examples (tried with chrome and firefox on windows 11), for instance https://www.cornerstonejs.org/live-examples/doubleclickwithstackannotationtools
3. observe that you can render some lines with the default tool (length)
4. alt tab to your external application (e.g. visual studio) and scroll using mouse wheel
5. alt tab back to the browser with the cornerstone3d example, observe that you can no longer render annotations

The following gif showcases just that:

![2023-08-09_17h04_53](https://github.com/cornerstonejs/cornerstone3D/assets/509192/581f9e23-5290-4130-ba53-6f8c072c9cd4)

what's interesting is that if you move switch to another window by clicking in the window (let's say you had the browser and visual studio side by side) and you just click in visual studio, scroll using the mouse wheel, and then come back to the browser, everything is working. The problem only occurs if we are using the alt+tab combination.

### The current behavior

something seems to be happening when we alt tab out of the browser and perform some input. The bug does not seem to occur if we simply alt tab, do nothing, and come back to the browser.

### The expected behavior

When I alt tab to another app and then come back to the browser, I expect to be able to continue using all the cornerstone tools on the image that's rendered.

### OS

Windows 11

### Node version

16.14.2

### Browser

chrome 115.0.5790.171 (Official Build) (64-bit), firefox 116.0.2 (64-bit)

**Comment by sedghi** [comment]
I can't reproduce what you say, did you try in-congnito? maybe you have some shortcuts/extensions that is messing with cs3d

![CleanShot 2023-08-15 at 10 24 01](https://github.com/cornerstonejs/cornerstone3D/assets/7490180/1b7adf59-461d-4ea2-a2ef-50b5bc5d6a6e)

**Comment by shikamu** [comment]
This issue is quite strange... I've tried in incognito, it's also happening, I've also tried in Edge, which is a browser I almost never use, same with firefox, so I'm confident I don't have any extra extensions for these.

I've just noticed that if you come back to the cornerstone3d app by pressing alt tab, the issue does not occur, it seems to occur if you click back in the browser that has the cornerstone app. I've recorded another demo:

![2023-08-16_07h22_31](https://github.com/cornerstonejs/cornerstone3D/assets/509192/76033914-eefd-4550-9185-8fa4f98c0fe1)

the first time, I draw a line, then I alt tab, I scroll in the new window, I click in the cornerstone window, and then I can't do anything anymore.
Then I refresh the page, draw a line again, alt tab, scroll in the new window, and alt tab back to the cornerstone app, and I guess this is what you did and yes indeed in that case apparently I'm able to render.

Are you able to reproduce my issue if you have 2 windows side by side, 1 with a cornerstone app and one with another browser window or w/e, draw a line in cornerstone, then alt tab, scroll in that new window and then click back in the cornerstone window and try to render another line, for me that does not work.

thanks for your time!

**Comment by shikamu** [comment]
@sedghi any thought ?

**Comment by diaztula** [comment]
I had the same issue and found that when you alt-tab to another window, then go back to the cornerstone tab and click (either left or right click), the mouse click event is triggered with the "ALT" key modifier on, even if you are no longer pressing the ALT key. 

In this situation the tool is not working anymore because the mouse click event does not match the initial mouse binging that is only mouse button, not button + ALT. The current active tool is not detected because of this.

I also found (similar to @HireGuerard) that if you press the ALT key, the tool works again, likely becase the ALT key modifier in the mouse click event is cleared when you release the ALT key.

A temporary workaround that works for my case is to add two bindings for the tool, one with the mouse button, and another with the mouse button plus the modifier key ALT.

`
toolGroup.setToolActive(yourToolName, {
  bindings: [
    {
       mouseButton: MouseBindings.Primary,
    },
    {
       mouseButton: MouseBindings.Primary,
       modifierKey: 18, // ALT key
     }
  ]
});
`
Please note this is a workaround and might not work for you if you use the ALT + click event to do someting else in your application.

**Comment by shikamu** [comment]
@jbocce thanks for the fix! I haven't tried the result of your PR but from what you describe in it, it seems to be spot on!

**Comment by diaztula** [comment]
Hello @jbocce, thanks for taking care of fixing this, seems to be a solution!
Cheers
