### ISSUE TITLE
setToolGroupToolStyles doesn't change the textBoxVisibility property

### ISSUE THREAD

**Issue by HussainHaider** [cornerstonejs/cornerstone3D#864]
### Describe the Bug

I'm using [Annotation Tool Modes](https://www.cornerstonejs.org/live-examples/annotationtoolmodes) example to change the style using configuration.  My intention is to hide the TextBox. I tried to use `textBoxVisibility: false`& `textBoxVisibility: '0'`. But nothing works and it still displays the TextBox. 

Following is my code

```
const styles = {
  LengthTool: {
    colorHighlighted: 'rgb(0, 4, 255)',
    textBoxVisibility: false,
  },
  global: {
    lineWidth: '2',
    textBoxVisibility: false,
    textBoxFontSize: '20px',
    textBoxLinkLineWidth: '5',
    textBoxBackground: 'rgb(0, 4, 255)',
  },
};

annotation.config.style.setToolGroupToolStyles(toolGroupId, styles);
```

### Steps to Reproduce

Just add the code in `Annotation Tool Modes` example code.

### The current behavior

![Screenshot from 2023-10-30 23-11-10](https://github.com/cornerstonejs/cornerstone3D/assets/21118650/b40e6827-f811-4587-b382-952f78e9d0a0)

### The expected behavior

The `textBox` should not be visible.

### OS

Ubuntu 22.04.2 LTS

### Node version

v19.4.0

### Browser

Chrome

**Comment by jlopes90** [comment]
https://github.com/cornerstonejs/cornerstone3D/blob/273effd7168aa5a0d5f788a691f616e6fd83b104/packages/tools/src/stateManagement/annotation/config/ToolStyle.ts#L223-L237

There was an error because false.

`if (styles[toolName] && styles[toolName][property])` the property is false, so if answer is false.

**Comment by jlopes90** [comment]
https://github.com/cornerstonejs/cornerstone3D/blob/273effd7168aa5a0d5f788a691f616e6fd83b104/packages/tools/src/stateManagement/annotation/config/ToolStyle.ts#L223-L237

There was an error because it says false is ignored.

`if (styles[toolName] && styles[toolName][property]) {` the property is false, so if answer is false.
