### ISSUE TITLE
[Bug] beforeSend() isn't being called by dicom-image-loader

### ISSUE THREAD

**Issue by tcarterBAMF** [cornerstonejs/cornerstone3D#915]
### Describe the Bug

`beforeSend` does not seem to be invoked when the image loader is configured like the following and trying to load `wadors:` images.

```javascript
  cornerstoneDICOMImageLoader.configure({
    beforeSend: function() {
      console.log("DICOMImageLoader beforeSend", arguments);
    },
  });
```

### Steps to Reproduce

1. Configure `cornerstoneDICOMImageLoader` with a `beforeSend` handler
2. Retrieve series metadata with `DICOMWebClient` and add them to `cornerstoneDICOMImageLoader.wadors.metaDataManager`
3. Create and cache a volume with the imageIds from the series
4. Call `load()` on the volume

### The current behavior

The `beforeSend` handler, which would add a needed authorization header,  is not called and so the image loader requests fail.

DICOMWebClient is configured to add the bearer header in a different way and so the metadata retrieval works fine.

### The expected behavior

The `beforeSend` handler is called before the image loader makes its request so I can add the bearer token header.

### OS

macos 12.6.2

### Node version

18.18.2

### Browser

Chrome 119.0.6045.159

**Comment by narbek-abd** [comment]
+1. Same problem. Did you find some workaround? I use OHIF v3 with auth tokens and we needed HTJ2K feature but after this  beforesend is not being called

**Comment by sedghi** [comment]
We are aware of this regression, and trying to fix it as soon as possible

**Comment by sedghi** [comment]
It is fixed

**Comment by shivam-pandey-qss** [comment]
I am passing a Bearer token in two places within the OHIF codebase to authenticate API requests, but the token is not being sent when retrieving the first frame. As a result, the UI breaks. However, for all other API requests, the Bearer token is being sent successfully.

1.In extensions/default/src/DicomWebDataSource/index.js

getAuthorizationHeader = () => {
const xhrRequestHeaders = {};
const authHeaders = userAuthenticationService.getAuthorizationHeader();
if (authHeaders && authHeaders.Authorization) {
xhrRequestHeaders.Authorization = authHeaders.Authorization;
}
xhrRequestHeaders.Authorization = Bearer ${dcm_token};
return xhrRequestHeaders;
};

2.In initWADOImageLoader

beforeSend: function (xhr) {
const dcm_token = sessionStorage.getItem('dcm4chee_token');
const sourceConfig = extensionManager.getActiveDataSource()?.[0].getConfig() ?? {};
const headers = userAuthenticationService.getAuthorizationHeader();
const acceptHeader = utils.generateAcceptHeader(
sourceConfig.acceptHeader,
sourceConfig.requestTransferSyntaxUID,
sourceConfig.omitQuotationForMultipartRequest
);

const xhrRequestHeaders = {
Accept: acceptHeader,
};
if (dcm_token) {
xhrRequestHeaders.Authorization = Bearer ${dcm_token};
}
if (headers) {
Object.assign(xhrRequestHeaders, headers);
}

return xhrRequestHeaders;
}

For the API request to retrieve the first frame, the Bearer token is not being sent, causing the UI to break. For all other subsequent API requests, the Bearer token is correctly included, and the APIs function as expected.
I suspect the issue is related to how the beforeSend logic is handled for the first frame, but I'm unsure how to resolve it. Any guidance or suggestions would be appreciated.


**The expected behavior**
All api's to DCM4CHEE should include the bearer token.
